--- 
"187: ruby 1.8.7 (2010-12-23 patchlevel 330) [i386-mingw32]": 
  :path: !ruby/object:Pathname 
    path: C:/Ruby187/bin
"192: ruby 1.9.2p136 (2010-12-25) [i386-mingw32]": 
  :path: !ruby/object:Pathname 
    path: C:/Ruby192/bin
--- {}

