#!/bin/sh
#  This bash script generated by Pik, the
#  Ruby Manager for Windows

export PATH='/c/Users/jcfuller/bin:.:/c/Program Files/Git/local/bin:/c/Program Files/Git/mingw/bin:/c/Program Files/Git/bin:/c/Ruby187/bin:/c/pik/:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/c/Program Files/Git/cmd:/c/Program Files/gittfs:/c/Program Files/Perforce:/c/Program Files/Vim/vim73'
export GEM_PATH=''
export GEM_HOME=''
